ports:
  - port: 8080

tasks:
- init: ./build-all.sh
- command: python3 -m http.server 8080
- command:  gp await-port 8080 &&
            echo "Browserify version at $(gp url 8080)/br" && 
            echo "Webpack version at $(gp url 8080)/wp" &&
            echo "Opening Webpack version in preview" && 
            gp preview $(gp url 8080)/wp